### ISSUE TITLE
Error message with example code

### ISSUE THREAD

**Issue by henricombrink** [ianmoran11/mmtable2#15]
When running the example code I get the following error:
`>  gm_df %>% 
mmtable2::mmtable(table_data = value)`
`Error in crossing(rows = 1:nrow(mmtable$`_data`), cols = 1:ncol(mmtable$`_data`)) : 
  unused arguments (rows = 1:nrow(mmtable$`_data`), cols = 1:ncol(mmtable$`_data`))`

R info:
`R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out `

**Comment by henricombrink** [comment]
The error has been resolved. It appears to have been a package conflict.

**Comment by ianmoran11** [comment]
Great - thanks for posting Henri. In case someone else comes across this error, I've added a fix on the branch I'm currently working on, which you can install with `remotes::install_github("ianmoran11/mmtable2@pipesyntax")`. I'm aiming to fix  remaining namespace issues this weekend.
