### ISSUE TITLE
Reordering factor levels for `header_top` and `header_top_left`

### ISSUE THREAD

**Issue by lilyclements** [ianmoran11/mmtable2#16]
The package is looking really nice. I just had one query - `mmtable` reorders the factor levels in the column factor variables, for example,

```
library(tidyverse)
library(mmtable2)
data(iris)

iris_summary <- iris %>%
  group_by(Species) %>%
  summarise(mean = mean(Sepal.Length), sum = sum(Sepal.Length)) %>%
  pivot_longer(cols = c(mean, sum))

levels(iris_summary$Species)
# currently Setosa, Versicolor, Virginica

levels(iris_summary$Species) <- c("C", "B", "A")

mmtable_iris <- iris_summary %>%
  mmtable(table_data = value, table_name = "Value")

mmtable_iris +
  header_top(Species) +
  header_left(name)

# the header labels are moved to be "A", "B", "C", rather than keeping the order of the factor levels, "C", "B", "A"
```

Firstly, why the factor levels are reordered?
Secondly is there is a way for the user to reorder these factor levels?

Thanks

**Comment by ianmoran11** [comment]
Thanks for posting this. The reordering isn't intended - I'll need to have a look for where its happening. 

This doesn't seem to be a problem for the left and left_top headers, they should give you a sense of how I expect top and top_left headers to work.

**Comment by ianmoran11** [comment]
I've just pushed some changes to fix this. You should be able to order top headers after reinstalling from github.

Thanks for the heads up!

cea683aeeb531927235db11687fcc28a0634f9e6

**Comment by lilyclements** [comment]
Excellent - thank you!
