### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by mgei** [ianmoran11/mmtable2#19]
```
> devtools::install_github("ianmoran11/mmtable2")
Downloading GitHub repo ianmoran11/mmtable2@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/ianmoran11/mmtable2/tarball/HEAD' failed
```

**Comment by ianmoran11** [comment]
Hi @mgei. Thanks for the heads up. I tested this on my computer and installed the package successfully.  Could you share a reprex (https://reprex.tidyverse.org/) with `reprex(..., session_info = TRUE)`?

**Comment by mgei** [comment]
Sorry, I had an outdated version of devtools. Installation worked after I updated.
